// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Event struct {
	ID          string         `json:"id"`
	BusinessID  string         `json:"business_id"`
	EventType   string         `json:"event_type"`
	Payload     string         `json:"payload"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	ProcessedAt sql.NullTime   `json:"processed_at"`
	Status      sql.NullString `json:"status"`
}

type Invoice struct {
	ID          string         `json:"id"`
	BusinessID  string         `json:"business_id"`
	Amount      float64        `json:"amount"`
	Currency    string         `json:"currency"`
	Status      string         `json:"status"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}
