// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	GetPendingEvents(ctx context.Context, limit int64) ([]Event, error)
	MarkEventAsProcessed(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
